### ISSUE TITLE
Windows: error generating report (ERR_CERT_COMMON_NAME_INVALID)

### ISSUE THREAD

**Issue by ebabeshko** [mahendrapaipuri/grafana-dashboard-reporter-app#31]
I'm using Grafana 10.2.6 for Windows

Installed and configured [Grafana Dashboard Reporter](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/src/README.md), but get 'error generating report' in browser when trying to generate a report

Used [this provisioning file](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/provisioning/plugins/app.yaml), but changed the following lines:

```
      appUrl: https://localhost:3000
      skipTlsCheck: true

```

Problem is the following:

```
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-05-09T13:28:17.4649117+03:00 level=info msg="Provisioned config" dashboardMode=default orientation=portrait persistData=false pluginID=mahendrapaipuri-dashboardreporter-app layout=simple maxRenderWorkers=2 appUrl=https://localhost:3000 dataPath=/var/lib/grafana endpoint=callResource skipTlsCheck=true
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-05-09T13:28:17.4659143+03:00 level=warn msg="failed to walk through grafana-image-renderer data dir" endpoint=callResource err="CreateFile \\var\\lib\\grafana\\plugins\\grafana-image-renderer: The system cannot find the path specified." pluginID=mahendrapaipuri-dashboardreporter-app
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-05-09T13:28:17.4659143+03:00 level=warn msg="Failed to get plugin app secret" endpoint=callResource err="PluginAppClientSecret not set in config" pluginID=mahendrapaipuri-dashboardreporter-app
logger=rendering renderer=plugin t=2024-05-09T13:28:17.4799092+03:00 level=info msg=Rendering path="d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=22&theme=light&to=now&width=1000"
logger=rendering renderer=plugin t=2024-05-09T13:28:17.4849103+03:00 level=info msg=Rendering path="d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=27&theme=light&to=now&width=1000"
logger=plugin.grafana-image-renderer t=2024-05-09T13:28:17.7719263+03:00 level=error msg="Browser request failed" url="https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=22&theme=light&to=now&width=1000&render=1" method=GET failure=net::ERR_CERT_COMMON_NAME_INVALID
logger=plugin.grafana-image-renderer t=2024-05-09T13:28:17.7719263+03:00 level=error msg="Browser request failed" url="https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=27&theme=light&to=now&width=1000&render=1" method=GET failure=net::ERR_CERT_COMMON_NAME_INVALID
logger=plugin.grafana-image-renderer t=2024-05-09T13:28:17.7729265+03:00 level=error msg="Error while trying to prepare page for screenshot" url="https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=27&theme=light&to=now&width=1000&render=1" err="Error: net::ERR_CERT_COMMON_NAME_INVALID at https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=27&theme=light&to=now&width=1000&render=1\n    at navigate (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Frame.js:114:23)\n    at async Deferred.race (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\util\\Deferred.js:82:20)\n    at async Frame.goto (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Frame.js:80:21)\n    at async CDPPage.goto (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Page.js:651:16)\n    at async Browser.takeScreenshot (C:\\snapshot\\src\\build\\browser\\browser.js:262:13)\n    at async Browser.render (C:\\snapshot\\src\\build\\browser\\browser.js:236:20)\n    at async PluginGRPCServer.render (C:\\snapshot\\src\\build\\plugin\\v2\\grpc_plugin.js:116:13)"
logger=plugin.grafana-image-renderer t=2024-05-09T13:28:17.7739264+03:00 level=error msg="Error while trying to prepare page for screenshot" url="https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=22&theme=light&to=now&width=1000&render=1" err="Error: net::ERR_CERT_COMMON_NAME_INVALID at https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=22&theme=light&to=now&width=1000&render=1\n    at navigate (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Frame.js:114:23)\n    at async Deferred.race (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\util\\Deferred.js:82:20)\n    at async Frame.goto (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Frame.js:80:21)\n    at async CDPPage.goto (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Page.js:651:16)\n    at async Browser.takeScreenshot (C:\\snapshot\\src\\build\\browser\\browser.js:262:13)\n    at async Browser.render (C:\\snapshot\\src\\build\\browser\\browser.js:236:20)\n    at async PluginGRPCServer.render (C:\\snapshot\\src\\build\\plugin\\v2\\grpc_plugin.js:116:13)"
```
Extract from C:\Program Files\GrafanaLabs\grafana\conf\defaults.ini

```
#################################### Server ##############################
[server]
protocol = https
min_tls_version = ""
http_addr =
http_port = 3000
domain = localhost
enforce_domain = false
```

It's not quite clear what should be done to solve this TLS-related issue for Grafana under Windows...

**Comment by ebabeshko** [comment]
Update: 
Used [this provisioning file](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/provisioning/plugins/app.yaml), but changed the following lines:

```
      appUrl: https://localhost:3000
      skipTlsCheck: true

```

Now problem is the following:

```
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-05-09T13:28:17.4649117+03:00 level=info msg="Provisioned config" dashboardMode=default orientation=portrait persistData=false pluginID=mahendrapaipuri-dashboardreporter-app layout=simple maxRenderWorkers=2 appUrl=https://localhost:3000 dataPath=/var/lib/grafana endpoint=callResource skipTlsCheck=true
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-05-09T13:28:17.4659143+03:00 level=warn msg="failed to walk through grafana-image-renderer data dir" endpoint=callResource err="CreateFile \\var\\lib\\grafana\\plugins\\grafana-image-renderer: The system cannot find the path specified." pluginID=mahendrapaipuri-dashboardreporter-app
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-05-09T13:28:17.4659143+03:00 level=warn msg="Failed to get plugin app secret" endpoint=callResource err="PluginAppClientSecret not set in config" pluginID=mahendrapaipuri-dashboardreporter-app
logger=rendering renderer=plugin t=2024-05-09T13:28:17.4799092+03:00 level=info msg=Rendering path="d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=22&theme=light&to=now&width=1000"
logger=rendering renderer=plugin t=2024-05-09T13:28:17.4849103+03:00 level=info msg=Rendering path="d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=27&theme=light&to=now&width=1000"
logger=plugin.grafana-image-renderer t=2024-05-09T13:28:17.7719263+03:00 level=error msg="Browser request failed" url="https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=22&theme=light&to=now&width=1000&render=1" method=GET failure=net::ERR_CERT_COMMON_NAME_INVALID
logger=plugin.grafana-image-renderer t=2024-05-09T13:28:17.7719263+03:00 level=error msg="Browser request failed" url="https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=27&theme=light&to=now&width=1000&render=1" method=GET failure=net::ERR_CERT_COMMON_NAME_INVALID
logger=plugin.grafana-image-renderer t=2024-05-09T13:28:17.7729265+03:00 level=error msg="Error while trying to prepare page for screenshot" url="https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=27&theme=light&to=now&width=1000&render=1" err="Error: net::ERR_CERT_COMMON_NAME_INVALID at https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=27&theme=light&to=now&width=1000&render=1\n    at navigate (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Frame.js:114:23)\n    at async Deferred.race (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\util\\Deferred.js:82:20)\n    at async Frame.goto (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Frame.js:80:21)\n    at async CDPPage.goto (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Page.js:651:16)\n    at async Browser.takeScreenshot (C:\\snapshot\\src\\build\\browser\\browser.js:262:13)\n    at async Browser.render (C:\\snapshot\\src\\build\\browser\\browser.js:236:20)\n    at async PluginGRPCServer.render (C:\\snapshot\\src\\build\\plugin\\v2\\grpc_plugin.js:116:13)"
logger=plugin.grafana-image-renderer t=2024-05-09T13:28:17.7739264+03:00 level=error msg="Error while trying to prepare page for screenshot" url="https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=22&theme=light&to=now&width=1000&render=1" err="Error: net::ERR_CERT_COMMON_NAME_INVALID at https://localhost:3000/d-solo/f9771316-6014-4402-943b-eaea3437f5f1/_?from=now-1h&height=500&panelId=22&theme=light&to=now&width=1000&render=1\n    at navigate (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Frame.js:114:23)\n    at async Deferred.race (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\util\\Deferred.js:82:20)\n    at async Frame.goto (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Frame.js:80:21)\n    at async CDPPage.goto (C:\\snapshot\\src\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\common\\Page.js:651:16)\n    at async Browser.takeScreenshot (C:\\snapshot\\src\\build\\browser\\browser.js:262:13)\n    at async Browser.render (C:\\snapshot\\src\\build\\browser\\browser.js:236:20)\n    at async PluginGRPCServer.render (C:\\snapshot\\src\\build\\plugin\\v2\\grpc_plugin.js:116:13)"
```

**Comment by mahendrapaipuri** [comment]
Hey @ebabeshko Cheers for the logs and config.

Very similar issue [here](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/issues/30#issuecomment-2102405939).

This line `logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-05-09T13:28:17.4659143+03:00 level=warn msg="failed to walk through grafana-image-renderer data dir" endpoint=callResource err="CreateFile \\var\\lib\\grafana\\plugins\\grafana-image-renderer: The system cannot find the path specified." pluginID=mahendrapaipuri-dashboardreporter-app
` tells me that you are running `grafana-image-renderer` as a separate service. Is that so? If so, please set  env vars `GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true` and `IGNORE_HTTPS_ERRORS=true` on the `grafana-image-renderer` server.

**Comment by ebabeshko** [comment]
@mahendrapaipuri , thank you for your fast reply. Looks like it was solved by adding the following lines to C:\Program Files\GrafanaLabs\grafana\conf\defauls.ini
```
[plugin.grafana-image-renderer]
rendering_ignore_https_errors = true
```
Now the following seems to prevent the successful report generation:
`
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-05-09T13:39:01.614007+03:00 level=warn msg="failed to walk through grafana-image-renderer data dir" endpoint=callResource err="CreateFile \\var\\lib\\grafana\\plugins\\grafana-image-renderer: The system cannot find the path specified." pluginID=mahendrapaipuri-dashboardreporter-app`

**Comment by mahendrapaipuri** [comment]
Thats great! Cheers, I will add that to docs.

As you are on Windows, you will have to set the `dataPath` in the provisioned config to the correct path. The default value is used in the config in the repo is for Linux. Check the [comments](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/7c39c319e7f74589aef3360d022bf59808ca0f04/provisioning/plugins/app.yaml#L51-L57) on how to set this for windows.

**Comment by ebabeshko** [comment]
The following change helped:
`      dataPath: C:\Program Files\GrafanaLabs\grafana\data`

I was confused by the following lines in [guide](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/src/README.md#grafana-related-parameters) 'dataPath: Grafana data path. By default on Linux deployment, it is /var/lib/grafana. **If a custom directory is used for paths.data in grafana.ini, the same path should be used for the dataPath**'. As I didn't change default location of path in Grafana config file, I didn't specify dataPath there as well...

Thank you very much for support. I was able to generate my first report successfully:

![report from Grafana Dashboard Reporter](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/63898296/1a998f71-3afd-46d8-8b7c-d0cab377bb92)

**Comment by mahendrapaipuri** [comment]
> I was confused by the following lines in [guide](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/src/README.md#grafana-related-parameters) 'dataPath: Grafana data path. By default on Linux deployment, it is /var/lib/grafana. If a custom directory is used for paths.data in grafana.ini, the same path should be used for the dataPath'.

Cheers for the pointer. You are right, I will have to rephrase that line.
